//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Question.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public Questions()
        {
            this.Answers1 = new HashSet<Answers1>();
        }
    
        public string QuestionText { get; set; }
        public string Answer1 { get; set; }
        public string Answer2 { get; set; }
        public string Answer3 { get; set; }
        public int QuestionID { get; set; }
    
        public virtual ICollection<Answers1> Answers1 { get; set; }
    }
}
