//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Question.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Answers1 = new HashSet<Answers1>();
        }
    
        public string Login { get; set; }
        public string Password { get; set; }
        public int UserID { get; set; }
        public int Years { get; set; }
    
        public virtual ICollection<Answers1> Answers1 { get; set; }
    }
}
