//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Question
{
    using System;
    using System.Collections.Generic;
    
    public partial class Бонусная_карта
    {
        public Бонусная_карта()
        {
            this.Клиент = new HashSet<Клиент>();
        }
    
        public int id__карты { get; set; }
        public Nullable<int> Скидка { get; set; }
        public Nullable<System.DateTime> Дата_регистрации { get; set; }
        public string Сумма_расходов { get; set; }
        public string ФИО { get; set; }
    
        public virtual ICollection<Клиент> Клиент { get; set; }
    }
}
