//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Question
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public Заказ()
        {
            this.Меню_Заказ = new HashSet<Меню_Заказ>();
            this.Счет = new HashSet<Счет>();
        }
    
        public string id_заказа { get; set; }
        public int id_клиента { get; set; }
        public int id_повара { get; set; }
        public Nullable<System.DateTime> Время_заказа { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual ICollection<Меню_Заказ> Меню_Заказ { get; set; }
        public virtual Повар Повар { get; set; }
        public virtual ICollection<Счет> Счет { get; set; }
    }
}
