//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Question
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиент
    {
        public Клиент()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public int id_клиента { get; set; }
        public Nullable<int> id__карты { get; set; }
    
        public virtual Бонусная_карта Бонусная_карта { get; set; }
        public virtual ICollection<Заказ> Заказ { get; set; }
    }
}
