//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Question
{
    using System;
    using System.Collections.Generic;
    
    public partial class Меню
    {
        public Меню()
        {
            this.Меню_Заказ = new HashSet<Меню_Заказ>();
        }
    
        public int id_блюда { get; set; }
        public string Название { get; set; }
        public Nullable<int> Цена { get; set; }
    
        public virtual ICollection<Меню_Заказ> Меню_Заказ { get; set; }
    }
}
